### ISSUE TITLE
Install using github version or pypi version?

### ISSUE THREAD

**Issue by 0xzkzhao** [ericsuh/dirichlet#4]
Hi, I notice that in the readme, you suggest install by 

`pip install git+https://github.com/ericsuh/dirichlet.git`

but there is also a `https://pypi.python.org/pypi/dirichlet`

Why not update the pypi one?

**Comment by 0xzkzhao** [comment]
Also, is there any example for using this package?

**Comment by ericsuh** [comment]
The github version is more likely to be up-to-date, although this package doesn't change often.

For examples for use, please see the test files
